### PR TITLE
Changes to the home page of the opwen client

### PR DESCRIPTION
**Pull request by sudheesh001**
These are the initial changes to the proposed changes for the new UI/UX.

# Home page
screen shot 2017-08-15 at 3 12 21 pm

# About
screen shot 2017-08-15 at 3 12 38 pm

##### Note: This patch isn't ready yet and needs work, there are a lot of inline css changes made during the hackathon.

### CODE REVIEW

**Comment by c-w** [comment]
Thanks for implementing this! In my queue to review this weekend.

**Comment by sudheesh001** [comment]
@c-w There are traces of inline css in this code, I'll move them out into the required files over the weekend. 👍

**Comment by c-w** [comment]
Alright, @sudheesh001, let me know when I should start to review this.

**Comment by c-w** [comment]
Hi @sudheesh001. Going to close this since the PR has been quiet for quite a while. Please re-open when you're ready to have your changes reviewed. Thanks in advance!

**Pull request closed without merging**
