### PR TITLE
Add admin option to configure APN

### PR DESCRIPTION
**Pull request by c-w**
Screenshot of settings page

Resolves https://github.com/ascoderu/opwen-webapp/issues/70

### CODE REVIEW

**Comment by nzola** [comment]
Great to see the Settings page. I see the page under the vwdial missing APN option.
I believe only the Admin will have the permissions to the Setting page and when he is not there he can make another user admin within the network.

**Comment by c-w** [comment]
@nzola The APN line will be there if the SIM information configured for the device has an APN line in it. This page lets the admin edit the entire wvdial.conf file that was generated for the device. The screenshot simply shows the default wvdial configuration which doesn't contain anything.

You're correct that only admins can view the settings page. Also, since https://github.com/ascoderu/opwen-webapp/pull/74 an admin can make another user admin, from the Users page (where admins can also suspend accounts or reset passwords):

Screenshot showing admin promotion option on Users page

Note that for now I've added logic that an admin can't "demote" another admin or change their password to prevent potential issues with one admin locking out themselves or everyone else (which is why next to the admin users marked with a star you can't see the suspend or promote options). Let me know if you'd like me to change this.

**Comment by nzola** [comment]
I like the way to implement the admin logic now. If I understand ; the initial admin of the Lokole can pass his admin power to another user. At this point the initial admin cannot take back his admin power, but only the new admin has the power to give it back to him or to someone else. Is this  correct? If yes, then this is the way I would love it to operate.

**Comment by c-w** [comment]
Thats correct, except that when the admin makes another user admin, they still keep their admin power; simply now there are two admins. Do you wish to only keep one admin on the device at any time? If so that's easy to implement, just let me know.

**Comment by nzola** [comment]
Let's just keep it as it is now. The implementation results will tell us which direction to go.

**Pull request merged**
